package br.com.driveme.entity;
// Generated 09/09/2018 21:13:34 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.beans.Transient;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "drivemedev_v1")
@JsonIgnoreProperties(value = {"pecas", "montadora"})
public class Modelo implements java.io.Serializable {

	private Long modeId;
	private Montadora montadora;
	private String modeDescricao;
	private Integer modeAno;
	private String modeIcone;
	private Set<Peca> pecas = new HashSet<Peca>(0);

	public Modelo() {
	}

	public Modelo(Long modeId, String modeDescricao, Integer modeAno, String modeIcone) {
		this.modeId = modeId;
		this.modeDescricao = modeDescricao;
		this.modeAno = modeAno;
		this.modeIcone = modeIcone;
	}

	public Modelo(Long modeId, String modeDescricao, Integer modeAno, String modeIcone, Set<Peca> pecas) {
		this.modeId = modeId;
		this.modeDescricao = modeDescricao;
		this.modeAno = modeAno;
		this.modeIcone = modeIcone;
		this.pecas = pecas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mode_id", unique = true, nullable = false)
	public Long getModeId() {
		return this.modeId;
	}

	public void setModeId(Long modeId) {
		this.modeId = modeId;
	}

	@Column(name = "mode_descricao", nullable = false, length = 100)
	public String getModeDescricao() {
		return this.modeDescricao;
	}

	public void setModeDescricao(String modeDescricao) {
		this.modeDescricao = modeDescricao;
	}

	@Column(name = "mode_ano", nullable = false)
	public Integer getModeAno() {
		return this.modeAno;
	}

	public void setModeAno(Integer modeAno) {
		this.modeAno = modeAno;
	}

	@Column(name = "mode_icone", nullable = false, length = 100)
	public String getModeIcone() {
		return this.modeIcone;
	}

	public void setModeIcone(String modeIcone) {
		this.modeIcone = modeIcone;
	}

	//@ManyToMany(fetch = FetchType.EAGER, mappedBy = "modelos")
	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "modelos")
	public Set<Peca> getPecas() {
		return this.pecas;
	}

	public void setPecas(Set<Peca> pecas) {
		this.pecas = pecas;
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mont_id", nullable = false)
	public Montadora getMontadora() {
		return montadora;
	}

	public void setMontadora(Montadora montadora) {
		this.montadora = montadora;
	}

}
