package br.com.driveme.entity;
// Generated 22/08/2018 18:35:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "driveme")
public class Modelo implements java.io.Serializable {

	private long modeId;
	private Montadora montadora;
	private String modeDescricao;
	private int modeAno;
	private Set<PecaModelo> pecaModelos = new HashSet(0);

	public Modelo() {
	}

	public Modelo(long modeId, Montadora montadora, String modeDescricao, int modeAno) {
		this.modeId = modeId;
		this.montadora = montadora;
		this.modeDescricao = modeDescricao;
		this.modeAno = modeAno;
	}

	public Modelo(long modeId, Montadora montadora, String modeDescricao, int modeAno, Set<PecaModelo> pecaModelos) {
		this.modeId = modeId;
		this.montadora = montadora;
		this.modeDescricao = modeDescricao;
		this.modeAno = modeAno;
		this.pecaModelos = pecaModelos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mode_id", unique = true, nullable = false)
	public long getModeId() {
		return this.modeId;
	}

	public void setModeId(long modeId) {
		this.modeId = modeId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mode_mont_id", nullable = false)
	public Montadora getMontadora() {
		return this.montadora;
	}

	public void setMontadora(Montadora montadora) {
		this.montadora = montadora;
	}

	@Column(name = "mode_descricao", nullable = false, length = 100)
	public String getModeDescricao() {
		return this.modeDescricao;
	}

	public void setModeDescricao(String modeDescricao) {
		this.modeDescricao = modeDescricao;
	}

	@Column(name = "mode_ano", nullable = false)
	public int getModeAno() {
		return this.modeAno;
	}

	public void setModeAno(int modeAno) {
		this.modeAno = modeAno;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "modelo")
	public Set<PecaModelo> getPecaModelos() {
		return this.pecaModelos;
	}

	public void setPecaModelos(Set<PecaModelo> pecaModelos) {
		this.pecaModelos = pecaModelos;
	}

}
