package br.com.driveme.entity;
// Generated 09/09/2018 21:13:34 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Modelo generated by hbm2java
 */
@Entity
@Table(name = "modelo", catalog = "driveme")
@JsonIgnoreProperties(value = {"pecas"})
public class Modelo implements java.io.Serializable {

	private long modeId;
	private Montadora montadora;
	private String modeDescricao;
	private int modeAno;
	private String modeIcone;
	private Set<Peca> pecas = new HashSet<Peca>(0);

	public Modelo() {
	}

	public Modelo(long modeId, Montadora montadora, String modeDescricao, int modeAno, String modeIcone) {
		this.modeId = modeId;
		this.montadora = montadora;
		this.modeDescricao = modeDescricao;
		this.modeAno = modeAno;
		this.modeIcone = modeIcone;
	}

	public Modelo(long modeId, Montadora montadora, String modeDescricao, int modeAno, String modeIcone, Set<Peca> pecas) {
		this.modeId = modeId;
		this.montadora = montadora;
		this.modeDescricao = modeDescricao;
		this.modeAno = modeAno;
		this.modeIcone = modeIcone;
		this.pecas = pecas;
	}

	@Id

	@Column(name = "mode_id", unique = true, nullable = false)
	public long getModeId() {
		return this.modeId;
	}

	public void setModeId(long modeId) {
		this.modeId = modeId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "mont_id", nullable = false)
	public Montadora getMontadora() {
		return this.montadora;
	}

	public void setMontadora(Montadora montadora) {
		this.montadora = montadora;
	}

	@Column(name = "mode_descricao", nullable = false, length = 100)
	public String getModeDescricao() {
		return this.modeDescricao;
	}

	public void setModeDescricao(String modeDescricao) {
		this.modeDescricao = modeDescricao;
	}

	@Column(name = "mode_ano", nullable = false)
	public int getModeAno() {
		return this.modeAno;
	}

	public void setModeAno(int modeAno) {
		this.modeAno = modeAno;
	}

	@Column(name = "mode_icone", nullable = false, length = 100)
	public String getModeIcone() {
		return this.modeIcone;
	}

	public void setModeIcone(String modeIcone) {
		this.modeIcone = modeIcone;
	}

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "modelos")
	public Set<Peca> getPecas() {
		return this.pecas;
	}

	public void setPecas(Set<Peca> pecas) {
		this.pecas = pecas;
	}

}
