package br.com.driveme.entity;
// Generated 22/08/2018 18:35:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * MontadoraTipoVeiculo generated by hbm2java
 */
@Entity
@Table(name = "montadora_tipo_veiculo", catalog = "driveme")
public class MontadoraTipoVeiculo implements java.io.Serializable {

	private long motiId;
	private Montadora montadora;
	private TipoVeiculo tipoVeiculo;

	public MontadoraTipoVeiculo() {
	}

	public MontadoraTipoVeiculo(long motiId, Montadora montadora, TipoVeiculo tipoVeiculo) {
		this.motiId = motiId;
		this.montadora = montadora;
		this.tipoVeiculo = tipoVeiculo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "moti_id", unique = true, nullable = false)
	public long getMotiId() {
		return this.motiId;
	}

	public void setMotiId(long motiId) {
		this.motiId = motiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moti_mont_id", nullable = false)
	public Montadora getMontadora() {
		return this.montadora;
	}

	public void setMontadora(Montadora montadora) {
		this.montadora = montadora;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "moti_veiculo_tive_id", nullable = false)
	public TipoVeiculo getTipoVeiculo() {
		return this.tipoVeiculo;
	}

	public void setTipoVeiculo(TipoVeiculo tipoVeiculo) {
		this.tipoVeiculo = tipoVeiculo;
	}

}
