package br.com.driveme.entity;
// Generated 09/09/2018 21:13:34 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Montadora generated by hbm2java
 */
@Entity
@Table(name = "montadora", catalog = "driveme")
@JsonIgnoreProperties(value = {"modelos"})
public class Montadora implements java.io.Serializable {

	private long montId;
	private String montDescricao;
	private String montIcone;
	private Set<Modelo> modelos = new HashSet<Modelo>(0);

	public Montadora() {
	}

	public Montadora(long montId, String montDescricao, String montIcone) {
		this.montId = montId;
		this.montDescricao = montDescricao;
		this.montIcone = montIcone;
	}

	public Montadora(long montId, String montDescricao, String montIcone, Set<Modelo> modelos) {
		this.montId = montId;
		this.montDescricao = montDescricao;
		this.montIcone = montIcone;
		this.modelos = modelos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mont_id", unique = true, nullable = false)
	public long getMontId() {
		return this.montId;
	}

	public void setMontId(long montId) {
		this.montId = montId;
	}

	@Column(name = "mont_descricao", nullable = false, length = 100)
	public String getMontDescricao() {
		return this.montDescricao;
	}

	public void setMontDescricao(String montDescricao) {
		this.montDescricao = montDescricao;
	}

	@Column(name = "mont_icone", nullable = false, length = 100)
	public String getMontIcone() {
		return this.montIcone;
	}

	public void setMontIcone(String montIcone) {
		this.montIcone = montIcone;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "montadora")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

}
