package br.com.driveme.entity;
// Generated 22/08/2018 18:35:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Montadora generated by hbm2java
 */
@Entity
@Table(name = "montadora", catalog = "driveme")
public class Montadora implements java.io.Serializable {

	private long montId;
	private String montDescricao;
	private Set<MontadoraTipoVeiculo> montadoraTipoVeiculos = new HashSet(0);
	private Set<Modelo> modelos = new HashSet(0);

	public Montadora() {
	}

	public Montadora(long montId, String montDescricao) {
		this.montId = montId;
		this.montDescricao = montDescricao;
	}

	public Montadora(long montId, String montDescricao, Set<MontadoraTipoVeiculo> montadoraTipoVeiculos, Set<Modelo> modelos) {
		this.montId = montId;
		this.montDescricao = montDescricao;
		this.montadoraTipoVeiculos = montadoraTipoVeiculos;
		this.modelos = modelos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mont_id", unique = true, nullable = false)
	public long getMontId() {
		return this.montId;
	}

	public void setMontId(long montId) {
		this.montId = montId;
	}

	@Column(name = "mont_descricao", nullable = false, length = 100)
	public String getMontDescricao() {
		return this.montDescricao;
	}

	public void setMontDescricao(String montDescricao) {
		this.montDescricao = montDescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "montadora")
	public Set<MontadoraTipoVeiculo> getMontadoraTipoVeiculos() {
		return this.montadoraTipoVeiculos;
	}

	public void setMontadoraTipoVeiculos(Set<MontadoraTipoVeiculo> montadoraTipoVeiculos) {
		this.montadoraTipoVeiculos = montadoraTipoVeiculos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "montadora")
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

}
