package br.com.driveme.entity;
// Generated 09/09/2018 21:13:34 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PecaImagem generated by hbm2java
 */
@Entity
@Table(name = "peca_imagem", catalog = "drivemedev_v1")
@JsonIgnoreProperties(value = {"peca"})
public class PecaImagem implements java.io.Serializable {

	private long peimId;
	private Peca peca;
	private String peimUrl;

	public PecaImagem() {
	}

	public PecaImagem(long peimId, Peca peca, String peimUrl) {
		this.peimId = peimId;
		this.peca = peca;
		this.peimUrl = peimUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "peim_id", unique = true, nullable = false)
	public long getPeimId() {
		return this.peimId;
	}

	public void setPeimId(long peimId) {
		this.peimId = peimId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "peca_id", nullable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

	@Column(name = "peim_url", nullable = false, length = 100)
	public String getPeimUrl() {
		return this.peimUrl;
	}

	public void setPeimUrl(String peimUrl) {
		this.peimUrl = peimUrl;
	}

}
