package br.com.driveme.entity;
// Generated 22/08/2018 18:35:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PecaModelo generated by hbm2java
 */
@Entity
@Table(name = "peca_modelo", catalog = "driveme")
public class PecaModelo implements java.io.Serializable {

	private long pemoId;
	private Modelo modelo;
	private Peca peca;

	public PecaModelo() {
	}

	public PecaModelo(long pemoId, Modelo modelo, Peca peca) {
		this.pemoId = pemoId;
		this.modelo = modelo;
		this.peca = peca;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pemo_id", unique = true, nullable = false)
	public long getPemoId() {
		return this.pemoId;
	}

	public void setPemoId(long pemoId) {
		this.pemoId = pemoId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pemo_mode_id", nullable = false)
	public Modelo getModelo() {
		return this.modelo;
	}

	public void setModelo(Modelo modelo) {
		this.modelo = modelo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pemo_peca_id", nullable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

}
