package br.com.driveme.entity;
// Generated 09/09/2018 21:13:34 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.hibernate.annotations.Proxy;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Peca generated by hbm2java
 */
@Entity
@Table(name = "peca", catalog = "drivemedev_v1")
@Proxy(lazy = false)
public class Peca implements java.io.Serializable {

	private long pecaId;
	private String pecaIdOriginal;
	private String pecaNome;
	private String pecaDescricao;
	private Integer pecaVisualizacao;
	private double pecaValor;
	private Set<PecaImagem> pecaImagems = new HashSet<PecaImagem>(0);
	private Set<Aplicacao> aplicacaos = new HashSet<Aplicacao>(0);
	private Set<PecaAvaliacao> pecaAvaliacaos = new HashSet<PecaAvaliacao>(0);
	private Set<PecaCaracteristica> pecaCaracteristicas = new HashSet<PecaCaracteristica>(0);
	private Set<PecaEspecificacao> pecaEspecificacaos = new HashSet<PecaEspecificacao>(0);
	private Set<Montadora> montadoras = new HashSet<Montadora>(0);
	private Set<Modelo> modelos = new HashSet<Modelo>(0);
	private Set<TipoVeiculo> tipoVeiculos = new HashSet<TipoVeiculo>(0);
	private Set<PecaPedido> pecaPedidos = new HashSet<PecaPedido>(0);
	
	private String valorPrincipal;
	private String valorCentavos;
	private Integer estrelas;

	public Peca() {
	}

	public Peca(long pecaId, String pecaIdOriginal, String pecaNome, String pecaDescricao, double pecaValor) {
		this.pecaId = pecaId;
		this.pecaIdOriginal = pecaIdOriginal;
		this.pecaNome = pecaNome;
		this.pecaDescricao = pecaDescricao;
		this.pecaValor = pecaValor;
	}

	public Peca(long pecaId, String pecaIdOriginal, String pecaNome, String pecaDescricao, Integer pecaVisualizacao, double pecaValor,
			Set<PecaImagem> pecaImagems, Set<Aplicacao> aplicacaos, Set<PecaAvaliacao> pecaAvaliacaos, Set<PecaCaracteristica> pecaCaracteristicas, Set<PecaEspecificacao> pecaEspecificacaos, Set<Montadora> montadoras, Set<Modelo> modelos, Set<TipoVeiculo> tipoVeiculos, Set<PecaPedido> pecaPedidos) {
		this.pecaId = pecaId;
		this.pecaIdOriginal = pecaIdOriginal;
		this.pecaNome = pecaNome;
		this.pecaDescricao = pecaDescricao;
		this.pecaVisualizacao = pecaVisualizacao;
		this.pecaValor = pecaValor;
		this.pecaImagems = pecaImagems;
		this.aplicacaos = aplicacaos;
		this.pecaAvaliacaos = pecaAvaliacaos;
		this.pecaCaracteristicas = pecaCaracteristicas;
		this.pecaEspecificacaos = pecaEspecificacaos;
		this.montadoras = montadoras;
		this.modelos = modelos;
		this.tipoVeiculos = tipoVeiculos;
		this.pecaPedidos = pecaPedidos;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "peca_id", unique = true, nullable = false)
	public long getPecaId() {
		return this.pecaId;
	}

	public void setPecaId(long pecaId) {
		this.pecaId = pecaId;
	}

	@Column(name = "peca_id_original", nullable = false, length = 45)
	public String getPecaIdOriginal() {
		return this.pecaIdOriginal;
	}

	public void setPecaIdOriginal(String pecaIdOriginal) {
		this.pecaIdOriginal = pecaIdOriginal;
	}

	@Column(name = "peca_nome", length = 150)
	public String getPecaNome() {
		return this.pecaNome;
	}

	public void setPecaNome(String pecaNome) {
		this.pecaNome = pecaNome;
	}

	@Column(name = "peca_descricao", nullable = false)
	public String getPecaDescricao() {
		return this.pecaDescricao;
	}

	public void setPecaDescricao(String pecaDescricao) {
		this.pecaDescricao = pecaDescricao;
	}

	@Column(name = "peca_visualizacao")
	public Integer getPecaVisualizacao() {
		return this.pecaVisualizacao;
	}

	public void setPecaVisualizacao(Integer pecaVisualizacao) {
		this.pecaVisualizacao = pecaVisualizacao;
	}

	@Column(name = "peca_valor", nullable = false, precision = 22, scale = 0)
	public double getPecaValor() {
		return this.pecaValor;
	}

	public void setPecaValor(double pecaValor) {
		this.pecaValor = pecaValor;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "peca")
	public Set<PecaImagem> getPecaImagems() {
		return this.pecaImagems;
	}

	public void setPecaImagems(Set<PecaImagem> pecaImagems) {
		this.pecaImagems = pecaImagems;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "peca_aplicacao", catalog = "drivemedev_v1", joinColumns = {
			@JoinColumn(name = "peca_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "apli_id", nullable = false, updatable = false) })
	public Set<Aplicacao> getAplicacaos() {
		return this.aplicacaos;
	}

	public void setAplicacaos(Set<Aplicacao> aplicacaos) {
		this.aplicacaos = aplicacaos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "peca")
	public Set<PecaAvaliacao> getPecaAvaliacaos() {
		return this.pecaAvaliacaos;
	}

	public void setPecaAvaliacaos(Set<PecaAvaliacao> pecaAvaliacaos) {
		this.pecaAvaliacaos = pecaAvaliacaos;
	}
	
	@OneToMany(fetch = FetchType.EAGER, mappedBy = "peca")
	public Set<PecaCaracteristica> getPecaCaracteristicas() {
		return this.pecaCaracteristicas;
	}

	public void setPecaCaracteristicas(Set<PecaCaracteristica> pecaCaracteristicas) {
		this.pecaCaracteristicas = pecaCaracteristicas;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "peca")
	public Set<PecaEspecificacao> getPecaEspecificacaos() {
		return this.pecaEspecificacaos;
	}

	public void setPecaEspecificacaos(Set<PecaEspecificacao> pecaEspecificacaos) {
		this.pecaEspecificacaos = pecaEspecificacaos;
	}
	
	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "peca_montadora", catalog = "drivemedev_v1", joinColumns = {
			@JoinColumn(name = "peca_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "mont_id", nullable = false, updatable = false) })
	public Set<Montadora> getMontadoras() {
		return this.montadoras;
	}

	public void setMontadoras(Set<Montadora> montadoras) {
		this.montadoras = montadoras;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "peca_modelo", catalog = "drivemedev_v1", joinColumns = {
			@JoinColumn(name = "peca_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "mode_id", nullable = false, updatable = false) })
	public Set<Modelo> getModelos() {
		return this.modelos;
	}

	public void setModelos(Set<Modelo> modelos) {
		this.modelos = modelos;
	}

	@ManyToMany(fetch = FetchType.EAGER)
	@JoinTable(name = "peca_tipo_veiculo", catalog = "drivemedev_v1", joinColumns = {
			@JoinColumn(name = "peca_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "tive_id", nullable = false, updatable = false) })
	public Set<TipoVeiculo> getTipoVeiculos() {
		return this.tipoVeiculos;
	}

	public void setTipoVeiculos(Set<TipoVeiculo> tipoVeiculos) {
		this.tipoVeiculos = tipoVeiculos;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "peca")
	public Set<PecaPedido> getPecaPedidos() {
		return this.pecaPedidos;
	}

	public void setPecaPedidos(Set<PecaPedido> pecaPedidos) {
		this.pecaPedidos = pecaPedidos;
	}

	@Transient
	public String getValorPrincipal() {
		return valorPrincipal;
	}

	public void setValorPrincipal(String valorPrincipal) {
		this.valorPrincipal = valorPrincipal;
	}

	@Transient
	public String getValorCentavos() {
		return valorCentavos;
	}

	public void setValorCentavos(String valorCentavos) {
		this.valorCentavos = valorCentavos;
	}

	@Transient
	public Integer getEstrelas() {
		return estrelas;
	}

	public void setEstrelas(Integer estrelas) {
		this.estrelas = estrelas;
	}
	
	

}
	