package br.com.driveme.entity;
// Generated 09/09/2018 21:13:34 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * PecaAvaliacao generated by hbm2java
 */
@Entity
@Table(name = "peca_avaliacao", catalog = "driveme")
@JsonIgnoreProperties(value = "peca")
public class PecaAvaliacao implements java.io.Serializable {

	private long peavId;
	private Peca peca;
	private Usuario usuario;
	private int peavEstrelas;
	private String peavDescricao;

	public PecaAvaliacao() {
	}

	public PecaAvaliacao(long peavId, Peca peca, Usuario usuario, int peavEstrelas) {
		this.peavId = peavId;
		this.peca = peca;
		this.usuario = usuario;
		this.peavEstrelas = peavEstrelas;
	}

	public PecaAvaliacao(long peavId, Peca peca, Usuario usuario, int peavEstrelas, String peavDescricao) {
		this.peavId = peavId;
		this.peca = peca;
		this.usuario = usuario;
		this.peavEstrelas = peavEstrelas;
		this.peavDescricao = peavDescricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "peav_id", unique = true, nullable = false)
	public long getPeavId() {
		return this.peavId;
	}

	public void setPeavId(long peavId) {
		this.peavId = peavId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "peca_id", nullable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "usua_id", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "peav_estrelas", nullable = false)
	public int getPeavEstrelas() {
		return this.peavEstrelas;
	}

	public void setPeavEstrelas(int peavEstrelas) {
		this.peavEstrelas = peavEstrelas;
	}

	@Column(name = "peav_descricao")
	public String getPeavDescricao() {
		return this.peavDescricao;
	}

	public void setPeavDescricao(String peavDescricao) {
		this.peavDescricao = peavDescricao;
	}

}
