package br.com.driveme.entity;
// Generated 22/08/2018 18:35:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PecaAvaliacao generated by hbm2java
 */
@Entity
@Table(name = "peca_avaliacao", catalog = "driveme")
public class PecaAvaliacao implements java.io.Serializable {

	private long peavId;
	private Peca peca;
	private int peavEstrelas;

	public PecaAvaliacao() {
	}

	public PecaAvaliacao(long peavId, Peca peca, int peavEstrelas) {
		this.peavId = peavId;
		this.peca = peca;
		this.peavEstrelas = peavEstrelas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "peav_id", unique = true, nullable = false)
	public long getPeavId() {
		return this.peavId;
	}

	public void setPeavId(long peavId) {
		this.peavId = peavId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peav_peca_id", nullable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

	@Column(name = "peav_estrelas", nullable = false)
	public int getPeavEstrelas() {
		return this.peavEstrelas;
	}

	public void setPeavEstrelas(int peavEstrelas) {
		this.peavEstrelas = peavEstrelas;
	}

}
