package br.com.driveme.entity;
// Generated 22/08/2018 18:35:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "driveme")
public class Pedido implements java.io.Serializable {

	private long pediId;
	private Usuario usuario;
	private Date pediData;
	private Double pediSubtotal;
	private Double pediTotal;
	private Set<PecaPedido> pecaPedidos = new HashSet(0);

	public Pedido() {
	}

	public Pedido(long pediId, Usuario usuario) {
		this.pediId = pediId;
		this.usuario = usuario;
	}

	public Pedido(long pediId, Usuario usuario, Date pediData, Double pediSubtotal, Double pediTotal, Set<PecaPedido> pecaPedidos) {
		this.pediId = pediId;
		this.usuario = usuario;
		this.pediData = pediData;
		this.pediSubtotal = pediSubtotal;
		this.pediTotal = pediTotal;
		this.pecaPedidos = pecaPedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pedi_id", unique = true, nullable = false)
	public long getPediId() {
		return this.pediId;
	}

	public void setPediId(long pediId) {
		this.pediId = pediId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pedi_usua_id", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pedi_data", length = 19)
	public Date getPediData() {
		return this.pediData;
	}

	public void setPediData(Date pediData) {
		this.pediData = pediData;
	}

	@Column(name = "pedi_subtotal", precision = 22, scale = 0)
	public Double getPediSubtotal() {
		return this.pediSubtotal;
	}

	public void setPediSubtotal(Double pediSubtotal) {
		this.pediSubtotal = pediSubtotal;
	}

	@Column(name = "pedi_total", precision = 22, scale = 0)
	public Double getPediTotal() {
		return this.pediTotal;
	}

	public void setPediTotal(Double pediTotal) {
		this.pediTotal = pediTotal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<PecaPedido> getPecaPedidos() {
		return this.pecaPedidos;
	}

	public void setPecaPedidos(Set<PecaPedido> pecaPedidos) {
		this.pecaPedidos = pecaPedidos;
	}

}
