package br.com.driveme.entity;
// Generated 17/08/2018 13:22:32 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TipoUsuario generated by hbm2java
 */
@Entity
@Table(name = "tipo_usuario", catalog = "driveme")
public class TipoUsuario implements java.io.Serializable {

	private long tiusId;
	private String tiusDescricao;

	public TipoUsuario() {
	}


	public TipoUsuario(long tiusId, String tiusDescricao) {
		this.tiusId = tiusId;
		this.tiusDescricao = tiusDescricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tius_id", unique = true, nullable = false)
	public long getTiusId() {
		return this.tiusId;
	}

	public void setTiusId(long tiusId) {
		this.tiusId = tiusId;
	}

	@Column(name = "tius_descricao", nullable = false, length = 45)
	public String getTiusDescricao() {
		return this.tiusDescricao;
	}

	public void setTiusDescricao(String tiusDescricao) {
		this.tiusDescricao = tiusDescricao;
	}

}
