package br.com.driveme.entity;
// Generated 22/08/2018 18:35:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoVeiculo generated by hbm2java
 */
@Entity
@Table(name = "tipo_veiculo", catalog = "driveme")
public class TipoVeiculo implements java.io.Serializable {

	private long tiveId;
	private String tiveDescricao;
	private Set<MontadoraTipoVeiculo> montadoraTipoVeiculos = new HashSet(0);

	public TipoVeiculo() {
	}

	public TipoVeiculo(long tiveId, String tiveDescricao) {
		this.tiveId = tiveId;
		this.tiveDescricao = tiveDescricao;
	}

	public TipoVeiculo(long tiveId, String tiveDescricao, Set<MontadoraTipoVeiculo> montadoraTipoVeiculos) {
		this.tiveId = tiveId;
		this.tiveDescricao = tiveDescricao;
		this.montadoraTipoVeiculos = montadoraTipoVeiculos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tive_id", unique = true, nullable = false)
	public long getTiveId() {
		return this.tiveId;
	}

	public void setTiveId(long tiveId) {
		this.tiveId = tiveId;
	}

	@Column(name = "tive_descricao", nullable = false, length = 100)
	public String getTiveDescricao() {
		return this.tiveDescricao;
	}

	public void setTiveDescricao(String tiveDescricao) {
		this.tiveDescricao = tiveDescricao;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoVeiculo")
	public Set<MontadoraTipoVeiculo> getMontadoraTipoVeiculos() {
		return this.montadoraTipoVeiculos;
	}

	public void setMontadoraTipoVeiculos(Set<MontadoraTipoVeiculo> montadoraTipoVeiculos) {
		this.montadoraTipoVeiculos = montadoraTipoVeiculos;
	}

}
