package br.com.driveme.entity;
// Generated 22/08/2018 18:35:11 by Hibernate Tools 5.2.11.Final

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "driveme")
public class Usuario implements java.io.Serializable {

	private long usuaId;
	private TipoUsuario tipoUsuario;
	private String usuaNome;
	private String usuaEmail;
	private String usuaSenha;
	private Set<UsuarioAvaliacao> usuarioAvaliacaos = new HashSet(0);
	private Set<Pedido> pedidos = new HashSet(0);

	public Usuario() {
	}

	public Usuario(long usuaId, TipoUsuario tipoUsuario) {
		this.usuaId = usuaId;
		this.tipoUsuario = tipoUsuario;
	}

	public Usuario(long usuaId, TipoUsuario tipoUsuario, String usuaNome, String usuaEmail, String usuaSenha,
			Set<UsuarioAvaliacao> usuarioAvaliacaos, Set<Pedido> pedidos) {
		this.usuaId = usuaId;
		this.tipoUsuario = tipoUsuario;
		this.usuaNome = usuaNome;
		this.usuaEmail = usuaEmail;
		this.usuaSenha = usuaSenha;
		this.usuarioAvaliacaos = usuarioAvaliacaos;
		this.pedidos = pedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "usua_id", unique = true, nullable = false)
	public long getUsuaId() {
		return this.usuaId;
	}

	public void setUsuaId(long usuaId) {
		this.usuaId = usuaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usua_tius_id", nullable = false)
	public TipoUsuario getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Column(name = "usua_nome", length = 100)
	public String getUsuaNome() {
		return this.usuaNome;
	}

	public void setUsuaNome(String usuaNome) {
		this.usuaNome = usuaNome;
	}

	@Column(name = "usua_email", length = 100)
	public String getUsuaEmail() {
		return this.usuaEmail;
	}

	public void setUsuaEmail(String usuaEmail) {
		this.usuaEmail = usuaEmail;
	}

	@Column(name = "usua_senha", length = 100)
	public String getUsuaSenha() {
		return this.usuaSenha;
	}

	public void setUsuaSenha(String usuaSenha) {
		this.usuaSenha = usuaSenha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<UsuarioAvaliacao> getUsuarioAvaliacaos() {
		return this.usuarioAvaliacaos;
	}

	public void setUsuarioAvaliacaos(Set<UsuarioAvaliacao> usuarioAvaliacaos) {
		this.usuarioAvaliacaos = usuarioAvaliacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
