package br.com.driveme.hibernate;
// Generated 18/11/2018 00:04:27 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Montadora generated by hbm2java
 */
@Entity
@Table(name = "montadora", catalog = "drivemedev_v1")
public class Montadora implements java.io.Serializable {

	private Long montId;
	private String montDescricao;
	private String montIcone;
	private Set pecas = new HashSet(0);
	private Set modelos = new HashSet(0);

	public Montadora() {
	}

	public Montadora(String montDescricao, String montIcone) {
		this.montDescricao = montDescricao;
		this.montIcone = montIcone;
	}

	public Montadora(String montDescricao, String montIcone, Set pecas, Set modelos) {
		this.montDescricao = montDescricao;
		this.montIcone = montIcone;
		this.pecas = pecas;
		this.modelos = modelos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mont_id", unique = true, nullable = false)
	public Long getMontId() {
		return this.montId;
	}

	public void setMontId(Long montId) {
		this.montId = montId;
	}

	@Column(name = "mont_descricao", nullable = false, length = 100)
	public String getMontDescricao() {
		return this.montDescricao;
	}

	public void setMontDescricao(String montDescricao) {
		this.montDescricao = montDescricao;
	}

	@Column(name = "mont_icone", nullable = false, length = 100)
	public String getMontIcone() {
		return this.montIcone;
	}

	public void setMontIcone(String montIcone) {
		this.montIcone = montIcone;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "montadoras")
	public Set getPecas() {
		return this.pecas;
	}

	public void setPecas(Set pecas) {
		this.pecas = pecas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "montadora")
	public Set getModelos() {
		return this.modelos;
	}

	public void setModelos(Set modelos) {
		this.modelos = modelos;
	}

}
