package br.com.driveme.hibernate;
// Generated 17/11/2018 23:52:37 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PecaAvaliacao generated by hbm2java
 */
@Entity
@Table(name = "peca_avaliacao", catalog = "drivemedev_v1")
public class PecaAvaliacao implements java.io.Serializable {

	private Long peavId;
	private Peca peca;
	private Usuario usuario;
	private int peavEstrelas;
	private String peavDescricao;
	private Date peavData;

	public PecaAvaliacao() {
	}

	public PecaAvaliacao(Peca peca, Usuario usuario, int peavEstrelas) {
		this.peca = peca;
		this.usuario = usuario;
		this.peavEstrelas = peavEstrelas;
	}

	public PecaAvaliacao(Peca peca, Usuario usuario, int peavEstrelas, String peavDescricao, Date peavData) {
		this.peca = peca;
		this.usuario = usuario;
		this.peavEstrelas = peavEstrelas;
		this.peavDescricao = peavDescricao;
		this.peavData = peavData;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "peav_id", unique = true, nullable = false)
	public Long getPeavId() {
		return this.peavId;
	}

	public void setPeavId(Long peavId) {
		this.peavId = peavId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peca_id", nullable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usua_id", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "peav_estrelas", nullable = false)
	public int getPeavEstrelas() {
		return this.peavEstrelas;
	}

	public void setPeavEstrelas(int peavEstrelas) {
		this.peavEstrelas = peavEstrelas;
	}

	@Column(name = "peav_descricao")
	public String getPeavDescricao() {
		return this.peavDescricao;
	}

	public void setPeavDescricao(String peavDescricao) {
		this.peavDescricao = peavDescricao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "peav_data", length = 19)
	public Date getPeavData() {
		return this.peavData;
	}

	public void setPeavData(Date peavData) {
		this.peavData = peavData;
	}

}
