package br.com.driveme.hibernate;
// Generated 18/11/2018 00:04:27 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PecaImagem generated by hbm2java
 */
@Entity
@Table(name = "peca_imagem", catalog = "drivemedev_v1")
public class PecaImagem implements java.io.Serializable {

	private Long peimId;
	private Peca peca;
	private String peimUrl;

	public PecaImagem() {
	}

	public PecaImagem(Peca peca, String peimUrl) {
		this.peca = peca;
		this.peimUrl = peimUrl;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "peim_id", unique = true, nullable = false)
	public Long getPeimId() {
		return this.peimId;
	}

	public void setPeimId(Long peimId) {
		this.peimId = peimId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peca_id", nullable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

	@Column(name = "peim_url", nullable = false, length = 100)
	public String getPeimUrl() {
		return this.peimUrl;
	}

	public void setPeimUrl(String peimUrl) {
		this.peimUrl = peimUrl;
	}

}
