package br.com.driveme.hibernate;
// Generated 17/11/2018 23:52:37 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Peca generated by hbm2java
 */
@Entity
@Table(name = "peca", catalog = "drivemedev_v1")
public class Peca implements java.io.Serializable {

	private Long pecaId;
	private String pecaIdOriginal;
	private String pecaNome;
	private String pecaDescricao;
	private Integer pecaVisualizacao;
	private double pecaValor;
	private Set pecaImagems = new HashSet(0);
	private Set wishlists = new HashSet(0);
	private Set aplicacaos = new HashSet(0);
	private Set pecaAvaliacaos = new HashSet(0);
	private Set pecaCaracteristicas = new HashSet(0);
	private Set pecaEspecificacaos = new HashSet(0);
	private Set montadoras = new HashSet(0);
	private Set modelos = new HashSet(0);
	private Set tipoVeiculos = new HashSet(0);
	private Set pecaPedidos = new HashSet(0);

	public Peca() {
	}

	public Peca(String pecaIdOriginal, String pecaNome, String pecaDescricao, double pecaValor) {
		this.pecaIdOriginal = pecaIdOriginal;
		this.pecaNome = pecaNome;
		this.pecaDescricao = pecaDescricao;
		this.pecaValor = pecaValor;
	}

	public Peca(String pecaIdOriginal, String pecaNome, String pecaDescricao, Integer pecaVisualizacao,
			double pecaValor, Set pecaImagems, Set wishlists, Set aplicacaos, Set pecaAvaliacaos,
			Set pecaCaracteristicas, Set pecaEspecificacaos, Set montadoras, Set modelos, Set tipoVeiculos,
			Set pecaPedidos) {
		this.pecaIdOriginal = pecaIdOriginal;
		this.pecaNome = pecaNome;
		this.pecaDescricao = pecaDescricao;
		this.pecaVisualizacao = pecaVisualizacao;
		this.pecaValor = pecaValor;
		this.pecaImagems = pecaImagems;
		this.wishlists = wishlists;
		this.aplicacaos = aplicacaos;
		this.pecaAvaliacaos = pecaAvaliacaos;
		this.pecaCaracteristicas = pecaCaracteristicas;
		this.pecaEspecificacaos = pecaEspecificacaos;
		this.montadoras = montadoras;
		this.modelos = modelos;
		this.tipoVeiculos = tipoVeiculos;
		this.pecaPedidos = pecaPedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "peca_id", unique = true, nullable = false)
	public Long getPecaId() {
		return this.pecaId;
	}

	public void setPecaId(Long pecaId) {
		this.pecaId = pecaId;
	}

	@Column(name = "peca_id_original", nullable = false, length = 45)
	public String getPecaIdOriginal() {
		return this.pecaIdOriginal;
	}

	public void setPecaIdOriginal(String pecaIdOriginal) {
		this.pecaIdOriginal = pecaIdOriginal;
	}

	@Column(name = "peca_nome", nullable = false, length = 150)
	public String getPecaNome() {
		return this.pecaNome;
	}

	public void setPecaNome(String pecaNome) {
		this.pecaNome = pecaNome;
	}

	@Column(name = "peca_descricao", nullable = false)
	public String getPecaDescricao() {
		return this.pecaDescricao;
	}

	public void setPecaDescricao(String pecaDescricao) {
		this.pecaDescricao = pecaDescricao;
	}

	@Column(name = "peca_visualizacao")
	public Integer getPecaVisualizacao() {
		return this.pecaVisualizacao;
	}

	public void setPecaVisualizacao(Integer pecaVisualizacao) {
		this.pecaVisualizacao = pecaVisualizacao;
	}

	@Column(name = "peca_valor", nullable = false, precision = 22, scale = 0)
	public double getPecaValor() {
		return this.pecaValor;
	}

	public void setPecaValor(double pecaValor) {
		this.pecaValor = pecaValor;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peca")
	public Set getPecaImagems() {
		return this.pecaImagems;
	}

	public void setPecaImagems(Set pecaImagems) {
		this.pecaImagems = pecaImagems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peca")
	public Set getWishlists() {
		return this.wishlists;
	}

	public void setWishlists(Set wishlists) {
		this.wishlists = wishlists;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "pecas")
	public Set getAplicacaos() {
		return this.aplicacaos;
	}

	public void setAplicacaos(Set aplicacaos) {
		this.aplicacaos = aplicacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peca")
	public Set getPecaAvaliacaos() {
		return this.pecaAvaliacaos;
	}

	public void setPecaAvaliacaos(Set pecaAvaliacaos) {
		this.pecaAvaliacaos = pecaAvaliacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peca")
	public Set getPecaCaracteristicas() {
		return this.pecaCaracteristicas;
	}

	public void setPecaCaracteristicas(Set pecaCaracteristicas) {
		this.pecaCaracteristicas = pecaCaracteristicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peca")
	public Set getPecaEspecificacaos() {
		return this.pecaEspecificacaos;
	}

	public void setPecaEspecificacaos(Set pecaEspecificacaos) {
		this.pecaEspecificacaos = pecaEspecificacaos;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "peca_montadora", catalog = "drivemedev_v1", joinColumns = {
			@JoinColumn(name = "peca_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "mont_id", nullable = false, updatable = false) })
	public Set getMontadoras() {
		return this.montadoras;
	}

	public void setMontadoras(Set montadoras) {
		this.montadoras = montadoras;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "peca_modelo", catalog = "drivemedev_v1", joinColumns = {
			@JoinColumn(name = "peca_id", nullable = false, updatable = false) }, inverseJoinColumns = {
					@JoinColumn(name = "mode_id", nullable = false, updatable = false) })
	public Set getModelos() {
		return this.modelos;
	}

	public void setModelos(Set modelos) {
		this.modelos = modelos;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "pecas")
	public Set getTipoVeiculos() {
		return this.tipoVeiculos;
	}

	public void setTipoVeiculos(Set tipoVeiculos) {
		this.tipoVeiculos = tipoVeiculos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "peca")
	public Set getPecaPedidos() {
		return this.pecaPedidos;
	}

	public void setPecaPedidos(Set pecaPedidos) {
		this.pecaPedidos = pecaPedidos;
	}

}
