package br.com.driveme.hibernate;
// Generated 17/11/2018 23:52:37 by Hibernate Tools 5.2.11.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "drivemedev_v1")
public class Pedido implements java.io.Serializable {

	private Long pediId;
	private Usuario usuario;
	private Date pediData;
	private Double pediSubtotal;
	private Double pediTotal;
	private Byte pediAberto;
	private Set pecaPedidos = new HashSet(0);

	public Pedido() {
	}

	public Pedido(Usuario usuario) {
		this.usuario = usuario;
	}

	public Pedido(Usuario usuario, Date pediData, Double pediSubtotal, Double pediTotal, Byte pediAberto,
			Set pecaPedidos) {
		this.usuario = usuario;
		this.pediData = pediData;
		this.pediSubtotal = pediSubtotal;
		this.pediTotal = pediTotal;
		this.pediAberto = pediAberto;
		this.pecaPedidos = pecaPedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "pedi_id", unique = true, nullable = false)
	public Long getPediId() {
		return this.pediId;
	}

	public void setPediId(Long pediId) {
		this.pediId = pediId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usua_id", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "pedi_data", length = 19)
	public Date getPediData() {
		return this.pediData;
	}

	public void setPediData(Date pediData) {
		this.pediData = pediData;
	}

	@Column(name = "pedi_subtotal", precision = 22, scale = 0)
	public Double getPediSubtotal() {
		return this.pediSubtotal;
	}

	public void setPediSubtotal(Double pediSubtotal) {
		this.pediSubtotal = pediSubtotal;
	}

	@Column(name = "pedi_total", precision = 22, scale = 0)
	public Double getPediTotal() {
		return this.pediTotal;
	}

	public void setPediTotal(Double pediTotal) {
		this.pediTotal = pediTotal;
	}

	@Column(name = "pedi_aberto")
	public Byte getPediAberto() {
		return this.pediAberto;
	}

	public void setPediAberto(Byte pediAberto) {
		this.pediAberto = pediAberto;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set getPecaPedidos() {
		return this.pecaPedidos;
	}

	public void setPecaPedidos(Set pecaPedidos) {
		this.pecaPedidos = pecaPedidos;
	}

}
