package br.com.driveme.hibernate;
// Generated 05/10/2018 12:48:45 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * UsuarioAvaliacao generated by hbm2java
 */
@Entity
@Table(name = "usuario_avaliacao", catalog = "drivemedev_v1")
public class UsuarioAvaliacao implements java.io.Serializable {

	private long usavId;
	private Usuario usuario;
	private int usavEstrelas;

	public UsuarioAvaliacao() {
	}

	public UsuarioAvaliacao(long usavId, Usuario usuario, int usavEstrelas) {
		this.usavId = usavId;
		this.usuario = usuario;
		this.usavEstrelas = usavEstrelas;
	}

	@Id

	@Column(name = "usav_id", unique = true, nullable = false)
	public long getUsavId() {
		return this.usavId;
	}

	public void setUsavId(long usavId) {
		this.usavId = usavId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usua_id", nullable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@Column(name = "usav_estrelas", nullable = false)
	public int getUsavEstrelas() {
		return this.usavEstrelas;
	}

	public void setUsavEstrelas(int usavEstrelas) {
		this.usavEstrelas = usavEstrelas;
	}

}
