package br.com.driveme.hibernate;
// Generated 17/11/2018 23:52:37 by Hibernate Tools 5.2.11.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", catalog = "drivemedev_v1")
public class Usuario implements java.io.Serializable {

	private Long usuaId;
	private TipoUsuario tipoUsuario;
	private String usuaNome;
	private String usuaEmail;
	private String usuaSenha;
	private Set pecaAvaliacaos = new HashSet(0);
	private Set usuarioAvaliacaos = new HashSet(0);
	private Set pedidos = new HashSet(0);
	private Set wishlists = new HashSet(0);

	public Usuario() {
	}

	public Usuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	public Usuario(TipoUsuario tipoUsuario, String usuaNome, String usuaEmail, String usuaSenha, Set pecaAvaliacaos,
			Set usuarioAvaliacaos, Set pedidos, Set wishlists) {
		this.tipoUsuario = tipoUsuario;
		this.usuaNome = usuaNome;
		this.usuaEmail = usuaEmail;
		this.usuaSenha = usuaSenha;
		this.pecaAvaliacaos = pecaAvaliacaos;
		this.usuarioAvaliacaos = usuarioAvaliacaos;
		this.pedidos = pedidos;
		this.wishlists = wishlists;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "usua_id", unique = true, nullable = false)
	public Long getUsuaId() {
		return this.usuaId;
	}

	public void setUsuaId(Long usuaId) {
		this.usuaId = usuaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tius_id", nullable = false)
	public TipoUsuario getTipoUsuario() {
		return this.tipoUsuario;
	}

	public void setTipoUsuario(TipoUsuario tipoUsuario) {
		this.tipoUsuario = tipoUsuario;
	}

	@Column(name = "usua_nome", length = 100)
	public String getUsuaNome() {
		return this.usuaNome;
	}

	public void setUsuaNome(String usuaNome) {
		this.usuaNome = usuaNome;
	}

	@Column(name = "usua_email", length = 100)
	public String getUsuaEmail() {
		return this.usuaEmail;
	}

	public void setUsuaEmail(String usuaEmail) {
		this.usuaEmail = usuaEmail;
	}

	@Column(name = "usua_senha", length = 100)
	public String getUsuaSenha() {
		return this.usuaSenha;
	}

	public void setUsuaSenha(String usuaSenha) {
		this.usuaSenha = usuaSenha;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set getPecaAvaliacaos() {
		return this.pecaAvaliacaos;
	}

	public void setPecaAvaliacaos(Set pecaAvaliacaos) {
		this.pecaAvaliacaos = pecaAvaliacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set getUsuarioAvaliacaos() {
		return this.usuarioAvaliacaos;
	}

	public void setUsuarioAvaliacaos(Set usuarioAvaliacaos) {
		this.usuarioAvaliacaos = usuarioAvaliacaos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set pedidos) {
		this.pedidos = pedidos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	public Set getWishlists() {
		return this.wishlists;
	}

	public void setWishlists(Set wishlists) {
		this.wishlists = wishlists;
	}

}
