package br.com.driveme.hibernate;
// Generated 17/11/2018 23:52:37 by Hibernate Tools 5.2.11.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * WishlistId generated by hbm2java
 */
@Embeddable
public class WishlistId implements java.io.Serializable {

	private long usuaId;
	private long pecaId;

	public WishlistId() {
	}

	public WishlistId(long usuaId, long pecaId) {
		this.usuaId = usuaId;
		this.pecaId = pecaId;
	}

	@Column(name = "usua_id", nullable = false)
	public long getUsuaId() {
		return this.usuaId;
	}

	public void setUsuaId(long usuaId) {
		this.usuaId = usuaId;
	}

	@Column(name = "peca_id", nullable = false)
	public long getPecaId() {
		return this.pecaId;
	}

	public void setPecaId(long pecaId) {
		this.pecaId = pecaId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof WishlistId))
			return false;
		WishlistId castOther = (WishlistId) other;

		return (this.getUsuaId() == castOther.getUsuaId()) && (this.getPecaId() == castOther.getPecaId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getUsuaId();
		result = 37 * result + (int) this.getPecaId();
		return result;
	}

}
