package br.com.driveme.hibernate;
// Generated 17/11/2018 23:52:37 by Hibernate Tools 5.2.11.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Wishlist generated by hbm2java
 */
@Entity
@Table(name = "wishlist", catalog = "drivemedev_v1")
public class Wishlist implements java.io.Serializable {

	private WishlistId id;
	private Peca peca;
	private Usuario usuario;

	public Wishlist() {
	}

	public Wishlist(WishlistId id, Peca peca, Usuario usuario) {
		this.id = id;
		this.peca = peca;
		this.usuario = usuario;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "usuaId", column = @Column(name = "usua_id", nullable = false)),
			@AttributeOverride(name = "pecaId", column = @Column(name = "peca_id", nullable = false)) })
	public WishlistId getId() {
		return this.id;
	}

	public void setId(WishlistId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "peca_id", nullable = false, insertable = false, updatable = false)
	public Peca getPeca() {
		return this.peca;
	}

	public void setPeca(Peca peca) {
		this.peca = peca;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "usua_id", nullable = false, insertable = false, updatable = false)
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

}
